# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Fred Jacobs - Fullstack .Net Developer"
email: your-email@domain.com
description: Fred Jacobs - Fullstack .Net Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jaxx-rep.github.io/" # the base hostname & protocol for your site
twitter_username: none
github_username:  Fred-Jacobs

# Build settings
markdown: kramdown
